name: Deploy to Firebase Hosting
on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out your repo
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Match your local Node version
      
      - name: Install dependencies and build
        run: |
          cd telehealth-frontend/  # Navigate to your frontend directory
          npm install
          npm run build
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_RTC_521A2 }}'
          projectId: fir-rtc-521a2  # Replace with your actual ID
          target: 'https://fir-rtc-521a2.firebaseapp.com'    # Optional: if you have multiple sites